// import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import fonts from './fonts'
// const inter = Inter({ subsets: ['latin'] })
// const outfit = Outfit({subsets:['latin']})

export const metadata = {
  title: 'Ahead Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.outfit.className}>{children}</body>
    </html>
  )
}
